export const hltWebsiteCopy = {
    th: {
        nav: {
            home: 'หน้าแรก',
            problem: 'ปัญหา',
            diagnostic: 'แบบเช็ก',
            audit: 'AIOS Audit',
            sectors: 'ธุรกิจที่ช่วย',
            insights: 'บทความ',
            cta: 'เริ่มเช็กฟรี',
            logoAlt: 'HighLevelThai',
            brandPrefix: 'HighLevel',
            brandAccent: 'Thai',
            menuOpen: 'เปิดเมนู',
            menuClose: 'ปิดเมนู',
        },
        hero: {
            eyebrow: 'HighLevelThai',
            title: 'ลูกค้าคุณกำลังหายไปโดยที่คุณไม่รู้ตัวหรือเปล่า?',
            subtitle: 'ธุรกิจบริการในกรุงเทพฯ ส่วนใหญ่ไม่ได้ขาดลูกค้า แต่กำลังเสียลูกค้าไประหว่างทาง',
            support: 'เช็กให้ชัดว่าลูกค้าหลุดตรงไหน ก่อนคุยเรื่องแก้ระบบ',
            primaryCta: 'เริ่มเช็กฟรี',
            secondaryCta: 'ดูขั้นตอนก่อนเช็ก',
            trustNote: 'เริ่มจากดูภาพรวมก่อน แล้วค่อยเช็ก 15 ข้อ ส่งผลใน LINE และดูต่อว่าควรทำ AIOS Audit หรือไม่',
            imageAlt: 'ช่างบริการกำลังตรวจงานหน้างาน',
        },
        problem: {
            kicker: 'ปัญหาจริง',
            title: 'ลูกค้าไม่ได้หายทีเดียว เขาหลุดเป็นจุด ๆ',
            intro: 'รอยรั่วเล็ก ๆ ในแต่ละช่วงทำให้รายได้หายไปทุกวัน โดยที่เจ้าของร้านมักไม่รู้ว่าหายไปตรงไหนกันแน่',
            items: [
                'ลูกค้าเห็นร้านคุณแล้ว แต่ไม่ทัก',
                'ลูกค้าทักมาแล้ว แต่คุณตอบไม่ทัน',
                'ลูกค้าถามราคาแล้ว แล้วก็หายไป',
                'ลูกค้าเคยใช้บริการแล้ว แต่ไม่กลับมาอีก',
            ],
            closing: 'นี่คือรอยรั่วที่ควรเห็นก่อนเพิ่มโฆษณา เพิ่มคน หรือเปลี่ยนวิธีทำงานทั้งระบบ',
        },
        newWay: {
            kicker: 'วิธีของ HLT',
            title: 'เราไม่เริ่มจากการขายระบบ',
            body: 'HLT เริ่มจากการดูว่าลูกค้าหลุดตรงไหนก่อน แล้วค่อยออกแบบสิ่งที่เหมาะกับธุรกิจจริงของคุณ',
            stagesTitle: 'AIOS ดู 5 จุดสำคัญ',
            stages: [
                { name: 'การเจอร้าน', label: 'ก่อนลูกค้าทัก', body: 'คนเห็นคุณแล้วเชื่อพอจะทักหรือยัง' },
                { name: 'การตอบกลับ', label: 'หลังลูกค้าทัก', body: 'ทักมาแล้วมีใครรับช่วงทันไหม' },
                { name: 'การปิดงาน', label: 'หลังถามราคา', body: 'ถามราคาแล้วมีเหตุผลให้เดินต่อหรือเปล่า' },
                { name: 'การส่งมอบงาน', label: 'ระหว่างให้บริการ', body: 'ระหว่างงานลูกค้ามั่นใจและเข้าใจพอไหม' },
                { name: 'การกลับมาใช้ซ้ำ', label: 'หลังจบงาน', body: 'จบงานแล้วมีทางดึงกลับมาไหม' },
            ],
        },
        freeDiagnostic: {
            kicker: 'เริ่มเบา ๆ',
            title: 'เริ่มจากแบบเช็กฟรี 15 ข้อ',
            body: 'ตอบตามสิ่งที่เกิดขึ้นจริงในธุรกิจของคุณ แล้วดูว่าช่วงไหนน่าจะทำให้งานรั่วมากที่สุด จากนั้นค่อยส่งผลมาใน LINE เพื่อดูว่าควรทำ AIOS Audit หรือไม่',
            bullets: ['คะแนนรอยรั่วของธุรกิจ', 'จุดที่ลูกค้าหลุดมากที่สุด', 'สิ่งที่ควรแก้ก่อน'],
            cta: 'เริ่มเช็กฟรี',
        },
        lineReview: {
            kicker: 'หลังเช็กเสร็จ',
            title: 'ส่งผลลัพธ์มาใน LINE แล้วเราช่วยดูให้',
            body: 'เราไม่ขายทันที เราดูให้ก่อนว่าลูกค้าหลุดตรงไหน ควรแก้ตรงไหนก่อน แล้วค่อยตัดสินใจว่าควรทำ AIOS Audit หรือเดินต่อแบบไหน',
            cta: 'คุยผ่าน LINE',
        },
        answers: {
            kicker: 'คำตอบสั้น ๆ',
            items: [
                {
                    question: 'HLT คืออะไร?',
                    answer: 'HLT เป็นจุดเริ่มต้นแบบ Diagnostic สำหรับเจ้าของธุรกิจบริการที่อยากรู้ว่าลูกค้าหลุดตรงไหนก่อน',
                },
                {
                    question: 'แบบเช็กฟรีช่วยอะไร?',
                    answer: 'ช่วยให้เห็นจุดรั่วแรก ว่าลูกค้ามักหยุดก่อนทัก หลังทัก หลังถามราคา หรือหลังจบงาน',
                },
                {
                    question: 'AIOS Audit คืออะไร?',
                    answer: 'เป็นการดูเส้นทางลูกค้าของธุรกิจคุณแบบทั้งภาพ เพื่อแยกว่าควรแก้อะไรก่อนจริง ๆ',
                },
                {
                    question: 'หลังจากนี้เกิดอะไรขึ้น?',
                    answer: 'เริ่มจากแบบเช็ก ส่งผลใน LINE แล้วค่อยตัดสินใจว่าจะทำ AIOS Audit และวางแผนติดตั้งต่อหรือไม่',
                },
            ],
        },
        audit: {
            kicker: 'AIOS Audit',
            title: 'AIOS Audit คือการดูธุรกิจของคุณแบบทั้งภาพ',
            body: 'เราไม่ได้ดูแค่เว็บไซต์ และไม่ได้ดูแค่ Facebook หรือ LINE แต่ดูว่าลูกค้าเห็นอะไร เชื่ออะไร ทักตรงไหน รอนานแค่ไหน และหลุดตรงไหน',
            reviewTitle: 'เราดูทั้งหน้าบ้านและหลังบ้าน',
            reviewItems: ['Google Maps / SEO', 'Facebook / Instagram', 'เส้นทางใน LINE', 'เว็บไซต์', 'รีวิว', 'ขั้นตอนการจอง', 'การตามต่อ', 'การดึงลูกค้ากลับมา'],
            deliveryTitle: 'รูปแบบการทำงาน',
            deliveryItems: ['ทำผ่านเซสชันออนไลน์', 'ทุกเซสชันถูกบันทึก', 'ใช้ทบทวนหรือสอนทีมได้', 'หากต้องการเข้าหน้างาน มีค่าใช้จ่ายเพิ่มเติม'],
            outputTitle: 'สิ่งที่คุณจะได้',
            outputs: ['แผนที่รอยรั่ว', 'จุดที่กระทบรายได้มากที่สุด', 'แผนงานชัดเจน', 'แผนติดตั้ง'],
        },
        implementation: {
            kicker: 'หลังเห็นภาพ',
            title: 'คุณเป็นคนเลือกว่าจะเริ่มตรงไหน',
            body: 'เราไม่บังคับ เราให้แผน แล้วคุณเลือกว่าจะทำอะไร ทำเมื่อไหร่ และทำแค่ไหน',
            options: [
                { title: 'ติดตั้งและส่งมอบให้ทีม', body: 'เราติดตั้งและสอนทีมคุณให้ดูแลต่อได้' },
                { title: 'ติดตั้งและดูแลต่อเนื่อง', body: 'เราติดตั้งและดูแลต่อรายเดือนให้ระบบเดินต่อเนื่อง' },
            ],
            principle: 'ติดตั้งเฉพาะสิ่งที่ Audit บอกว่าควรแก้',
        },
        sectors: {
            kicker: 'เหมาะกับใคร',
            title: 'สำหรับธุรกิจบริการที่งานหลุดเพราะลูกค้าเปรียบเทียบ ไม่มั่นใจ หรือรอนานเกินไป',
            items: [
                { label: 'ร้านแอร์', to: '/home-services' },
                { label: 'ช่างไฟ ช่างประปา', to: '/home-services' },
                { label: 'คลินิก', to: '/clinics' },
                { label: 'ร้านเสริมสวย', to: '/salons' },
                { label: 'ธุรกิจบริการทั่วไป', to: '/aios-diagnostic' },
            ],
        },
        areas: {
            kicker: 'ที่เราทำงานด้วย',
            title: 'ธุรกิจบริการในกรุงเทพฯ',
            items: ['สุขุมวิท', 'สีลม', 'สาทร', 'อารีย์', 'ลาดพร้าว', 'รัชดา', 'บางนา', 'พระราม 9', 'เอกมัย', 'ทองหล่อ'],
        },
        insights: {
            kicker: 'บริบท',
            title: 'คำถามที่ควรถามก่อนเปลี่ยนอะไร',
            body: 'บทความสั้น ๆ เกี่ยวกับรูปแบบที่ธุรกิจบริการไทยมักเจอก่อนจะรู้ว่าลูกค้าหลุดช่วงไหน',
            cards: [
                'ทำไมลูกค้าถามราคาแล้วเงียบ',
                'ก่อนเพิ่มโฆษณา ควรเช็กอะไร',
                'LINE ทำให้ปิดงานเร็วขึ้นได้อย่างไร',
            ],
        },
        finalCta: {
            title: 'ก่อนเพิ่มลูกค้าใหม่ เช็กก่อนว่าลูกค้าเดิมหลุดตรงไหน',
            body: 'เริ่มจากแบบเช็กฟรี ใช้เวลาไม่นาน แล้วส่งผลมาใน LINE เพื่อดูว่าควรทำ AIOS Audit และวางแผนติดตั้งอะไรต่อ',
            primaryCta: 'เริ่มเช็กฟรี',
            secondaryCta: 'คุยผ่าน LINE',
        },
        footer: {
            tagline: 'ช่วยธุรกิจบริการไทยหาว่าลูกค้าหลุดตรงไหน ก่อนติดตั้งอะไรเพิ่ม',
            brandPrefix: 'HighLevel',
            brandAccent: 'Thai',
            company: 'HLT',
            privacy: 'นโยบายความเป็นส่วนตัว',
            terms: 'เงื่อนไข',
            support: 'ติดต่อเรา',
            builtWith: 'ทำแบบตั้งใจทุกจุด',
            aiosDiagnostic: 'แบบเช็ก AIOS',
            startCheck: 'เริ่มเช็กฟรี',
        },
    },
    en: {
        nav: {
            home: 'Home',
            problem: 'Problem',
            diagnostic: 'Diagnostic',
            audit: 'AIOS Audit',
            sectors: 'Sectors',
            insights: 'Insights',
            cta: 'Start free check',
            logoAlt: 'HighLevelThai',
            brandPrefix: 'HighLevel',
            brandAccent: 'Thai',
            menuOpen: 'Open menu',
            menuClose: 'Close menu',
        },
        hero: {
            eyebrow: 'HighLevelThai',
            title: 'Are your customers disappearing without you realising it?',
            subtitle: 'Most Bangkok service businesses do not lack customers. They lose them along the way.',
            support: 'See clearly where customers drop off before discussing system fixes.',
            primaryCta: 'Start free check',
            secondaryCta: 'See the steps first',
            trustNote: 'Start with the overview, then take the 15-question check, send the result on LINE, and decide whether an AIOS Audit is needed.',
            imageAlt: 'A service technician checking work on site',
        },
        problem: {
            kicker: 'The real problem',
            title: 'Customers do not disappear all at once. They drop off at specific points.',
            intro: 'Small leaks across the journey quietly remove revenue every day, often before the owner can see where it happened.',
            items: ['Customers see your business, but do not message', 'Customers message, but you do not reply in time', 'Customers ask for price, then disappear', 'Customers have used your service, but never return'],
            closing: 'This is the leak to see before adding ads, hiring more people, or changing the whole workflow.',
        },
        newWay: {
            kicker: 'The HLT way',
            title: 'We do not start by selling systems',
            body: 'HLT starts by identifying where customers drop off, then designing what fits your actual business.',
            stagesTitle: 'AIOS reviews 5 key stages',
            stages: [
                { name: 'Discovery', label: 'Finding you', body: 'Do people trust you enough to message?' },
                { name: 'Response', label: 'Replying', body: 'Does someone respond while the job is still warm?' },
                { name: 'Conversion', label: 'Closing', body: 'Is there a reason to keep moving after price?' },
                { name: 'Delivery', label: 'Service delivery', body: 'Does the customer feel informed and confident?' },
                { name: 'Retention', label: 'Returning', body: 'Is there a path back after the job is done?' },
            ],
        },
        freeDiagnostic: {
            kicker: 'Light first step',
            title: 'Start with a free 15-question check',
            body: 'Answer based on what really happens in the business, see where jobs are most likely leaking, then send the result on LINE to see whether an AIOS Audit makes sense.',
            bullets: ['Business leakage score', 'The biggest drop-off point', 'What to fix first'],
            cta: 'Start free check',
        },
        lineReview: {
            kicker: 'After the check',
            title: 'Send your result on LINE and we will review it with you',
            body: 'We do not sell immediately. We first review where customers drop off, what should be fixed first, then decide whether an AIOS Audit is the right next step.',
            cta: 'Chat on LINE',
        },
        answers: {
            kicker: 'Quick answers',
            items: [
                {
                    question: 'What is HLT?',
                    answer: 'HLT is a diagnostic starting point for Thai service business owners who want to see where customers are dropping off first.',
                },
                {
                    question: 'What does the Free Check do?',
                    answer: 'It helps reveal the first likely leak, before messaging, after messaging, after pricing, or after the job is done.',
                },
                {
                    question: 'What is the AIOS Audit?',
                    answer: 'It is a full review of your customer journey so the business can see what should be fixed first.',
                },
                {
                    question: 'What happens next?',
                    answer: 'You start with the check, send the result on LINE, then decide whether AIOS Audit and implementation should follow.',
                },
            ],
        },
        audit: {
            kicker: 'AIOS Audit',
            title: 'The AIOS Audit reviews your business as a whole',
            body: 'We do not only look at your website, Facebook, or LINE. We review what customers see, what they believe, where they message, how long they wait, and where they drop off.',
            reviewTitle: 'We review front-end and back-end',
            reviewItems: ['Google Maps / SEO', 'Facebook / Instagram', 'LINE flow', 'Website', 'Reviews', 'Booking process', 'Follow-up', 'Repeat system'],
            deliveryTitle: 'Delivery model',
            deliveryItems: ['Online sessions', 'Every session is recorded', 'Use for review or team training', 'On-site is available at additional cost'],
            outputTitle: 'What you receive',
            outputs: ['Leakage map', 'The highest revenue-impact points', 'Clear roadmap', 'Implementation plan'],
        },
        implementation: {
            kicker: 'After the diagnosis',
            title: 'You choose where to start',
            body: 'We do not force. We provide the plan, then you choose what to do, when to do it, and how much to do.',
            options: [
                { title: 'Build and hand over to your team', body: 'We build and train your team to manage it.' },
                { title: 'Build and manage ongoing', body: 'We build and manage it monthly so the system keeps running.' },
            ],
            principle: 'Only build what the audit recommends fixing',
        },
        sectors: {
            kicker: 'Who this is for',
            title: 'For service businesses where jobs leak because customers cannot compare, trust, or get a reply in time',
            items: [
                { label: 'AC services', to: '/home-services' },
                { label: 'Trades', to: '/home-services' },
                { label: 'Clinics', to: '/clinics' },
                { label: 'Salons', to: '/salons' },
                { label: 'General service businesses', to: '/aios-diagnostic' },
            ],
        },
        areas: {
            kicker: 'Where we work',
            title: 'Bangkok-based service businesses',
            items: ['Sukhumvit', 'Silom', 'Sathorn', 'Ari', 'Ladprao', 'Ratchada', 'Bangna', 'Rama 9', 'Ekkamai', 'Thonglor'],
        },
        insights: {
            kicker: 'Context',
            title: 'Questions worth asking before changing anything',
            body: 'Short reads on the patterns Thai service businesses typically hit before they know where the leak is.',
            cards: ['Why customers ask for price and go quiet', 'What to check before adding ads', 'How LINE can help close jobs faster'],
        },
        finalCta: {
            title: 'Before getting more customers, check where you are losing them',
            body: 'Start with the free check, send the result on LINE, then decide whether an AIOS Audit and implementation should follow.',
            primaryCta: 'Start free check',
            secondaryCta: 'Chat on LINE',
        },
        footer: {
            tagline: 'Helping Thai service businesses find where customers disappear before installing anything new.',
            brandPrefix: 'HighLevel',
            brandAccent: 'Thai',
            company: 'HLT',
            privacy: 'Privacy Policy',
            terms: 'Terms',
            support: 'Contact',
            builtWith: 'Built with care.',
            aiosDiagnostic: 'AIOS Diagnostic',
            startCheck: 'Start free check',
        },
    },
};
