// opsCockpit.js — every visible string on /ops-cockpit.
//
// Each line below is lifted VERBATIM from a fenced block in the verified copy deck at
//   C:\Projects\IWT\02-builds\executive-assistant\work\drafts\2026-09-14-HLT-OPS-COCKPIT-PAGE-COPY.md
// Nothing here is the builder's own wording. Change the deck first, then this file. Proved by
//   node src/assets/brand/hlt-logo-v2/verify-page-copy.mjs ops-cockpit <deck path>
//
// PRICES. No THB figure is ruled for PC4 yet, so there is no price key and no price renders.
// The catalogue's monthly options are quoted in USD, so FAQ 5 names what they buy and no rate.
export const opsCockpitCopy = {
    ocpNavLink: 'Ops Cockpit',

    ocpMetaTitle: 'Ops Cockpit: a login-gated dashboard built in your accounts | High Level Thai',
    ocpMetaDescription: "A login-gated dashboard built on one rule: work that's done disappears, and the top of the page is whatever's waiting on you. For businesses across Thailand.",

    ocpHeroHeadline: "A dashboard built on one rule: work that's done disappears.",
    ocpHeroLead: "Most dashboards show you everything, which is why nobody opens them twice. This one is built to a single rule: disappear, not grey out. Work that's done vanishes off the screen, empty panels remove themselves, and the top of the page is whatever's waiting on you, what it's holding up, and how many minutes it'll cost to clear. It's login-gated, built in your own accounts, and we hold nothing after handover.",
    ocpCtaLabel: 'Talk to us on LINE',
    ocpHeroCtaNote: 'Delivery from seven days. Your login, your data, your domain.',

    ocpHeroImage: 'https://images.unsplash.com/photo-1556155092-490a1ba16284?auto=format&fit=crop&w=1600&q=70',
    ocpHeroImageAlt: 'A laptop on a wooden table showing a clean dashboard of figures.',

    ocpSummaryHeading: 'Nobody opens a dashboard that shows them everything.',
    ocpSummaryP1: "Most dashboards show you everything. That's why nobody opens them twice.",
    ocpSummaryP2: "This one is built to a single rule: disappear, not grey out. Work that's done vanishes off the screen. Empty panels remove themselves. The top of the page is whatever's waiting on you, what it's holding up, and how many minutes it'll cost to clear.",
    ocpSummaryP3: "It's a login-gated dashboard on Next.js, Supabase and Vercel, built in your accounts. Your login, your data, your domain. We get invited in, and we hold nothing after handover.",
    ocpSummaryP4: 'We agree what finished means before we write anything. The acceptance test document lists every panel, what it has to do and the pass condition, and we run it together at handover.',
    ocpSummaryP5: "We don't connect live third-party tools in this build. That's a separate job, and we'd rather quote it properly than promise it here.",
    ocpSummaryP6: 'We work with service businesses across Thailand, Hua Hin and Bangkok included.',

    ocpTiersHeading: 'Three depths. Same rule.',

    ocpTier1Name: 'Three Queues',
    ocpTier1Desc: 'Up to three work queues and the blockers panel, live on a Vercel subdomain.',
    ocpTier2Name: 'Working Cockpit',
    ocpTier2Desc: 'Five queues on your own domain, one write-back route, recorded handover.',
    ocpTier3Name: 'Full Cockpit and Runbook',
    ocpTier3Desc: 'Eight queues, two write-back routes, a bridge table, and a live handover.',

    ocpRow1Label: 'Delivery',
    ocpRow1A: '7 days',
    ocpRow1B: '12 days',
    ocpRow1C: '18 days',
    ocpRow2Label: 'Revisions',
    ocpRow2A: '1',
    ocpRow2B: '2',
    ocpRow2C: '3',
    ocpRow3Label: 'Work queues',
    ocpRow3A: 'Up to 3',
    ocpRow3B: 'Up to 5',
    ocpRow3C: 'Up to 8',
    ocpRow4Label: 'Open-blockers panel',
    ocpRow4A: 'Yes',
    ocpRow4B: 'Yes',
    ocpRow4C: 'Yes, with priority ordering rules',
    ocpRow5Label: 'Deployment',
    ocpRow5A: 'Vercel subdomain',
    ocpRow5B: 'Your custom domain',
    ocpRow5C: 'Your custom domain',
    ocpRow6Label: 'Write-back routes',
    ocpRow6A: '0',
    ocpRow6B: '1',
    ocpRow6C: '2',
    ocpRow7Label: 'Message or bridge table',
    ocpRow7A: 'No',
    ocpRow7B: 'No',
    ocpRow7C: 'Yes',
    ocpRow8Label: 'Seeded import',
    ocpRow8A: 'Seed data only',
    ocpRow8B: '1 CSV import',
    ocpRow8C: '2 CSV imports',
    ocpRow9Label: 'Acceptance test document',
    ocpRow9A: 'Yes',
    ocpRow9B: 'Yes',
    ocpRow9C: 'Yes',
    ocpRow10Label: 'Handover',
    ocpRow10A: 'Written notes',
    ocpRow10B: '20-min recorded video',
    ocpRow10C: '45-min session plus runbook',

    ocpIncludedHeading: 'What you get, on every tier',
    ocpIncluded1: 'A deployed, login-gated dashboard',
    ocpIncluded2: 'Your own Supabase project, with auth and tables',
    ocpIncluded3: 'One table per work queue, each with status, priority and opened_at',
    ocpIncluded4: 'The organising rule applied throughout: disappear, not grey out',
    ocpIncluded5: 'An open-blockers queue at the top showing, per item, what you do next, what it blocks and how many minutes it costs',
    ocpIncluded6: 'Schema and seed migrations',
    ocpIncluded7: 'An acceptance test document written before the build starts',
    ocpIncluded8: 'All credentials created in your accounts',

    ocpStepsHeading: 'How it runs',
    ocpStep1Lead: 'The queue list.',
    ocpStep1Body: 'You tell us the five to eight work queues your business actually runs, the statuses each one uses, and which status means done.',
    ocpStep2Lead: 'The acceptance test.',
    ocpStep2Body: 'Written before any code, listing every panel, what it has to do, and the condition that says it passed.',
    ocpStep3Lead: 'Schema and seed.',
    ocpStep3Body: 'Your own Supabase project, one table per queue, with status, priority and opened_at, plus seed data so you can see it working.',
    ocpStep4Lead: 'Build and deploy.',
    ocpStep4Body: 'Login-gated, on your Vercel account, on your domain if you want one.',
    ocpStep5Lead: 'Handover.',
    ocpStep5Body: 'We run the acceptance test together, then a recorded walkthrough and the runbook. Every credential is already in your name.',

    ocpFaqHeading: 'Questions owners ask first',
    ocpFaq1Q: "What's a queue, and what if I don't know mine yet?",
    ocpFaq1A: "A queue is a working list you move things down: enquiries in, quotes out, jobs on site, snagging. If you're not sure which are yours, start with the three you're surest of. More get added without a rebuild, because each is its own table.",
    ocpFaq2Q: 'Where does it live?',
    ocpFaq2A: 'In your accounts. Your Supabase project, your Vercel deployment, your domain. We hold nothing after handover.',
    ocpFaq3Q: 'Can it pull from my other tools?',
    ocpFaq3A: 'Not in this build. It runs work queues and blockers with a write-back route. Live third-party integrations are a separate job and get quoted separately.',
    ocpFaq4Q: "How do we agree it's finished?",
    ocpFaq4A: 'Against the acceptance test document, which lists each panel, its expected behaviour and the pass condition. We run it together at handover.',
    ocpFaq5Q: 'What about ongoing changes?',
    ocpFaq5A: 'Monthly options exist for data-source repair, new panels, and weekly review facilitation. Not required, and not bundled by default.',

    ocpClosingHeading: 'The screen you open first, with your work in it.',
    ocpClosingBody: 'Message us on LINE with the queues you actually run and which status means done. The acceptance test gets written before any code, so you know what finished looks like before we start.',
    ocpLineHandle: 'LINE Official Account',
};
